# 服务器启动端口
server:
  port: 8086


#spring
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3307/activity?serverTimezone=GMT%2B8
    #url: jdbc:mysql://localhost:3306/activity?useUnicode=true&characterEncoding=UTF-8&userSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  #activiti
  activiti:
    database-schema-update: true
    check-process-definitions: true
    process-definition-location-prefix: classpath:/process/
    history-level: full


#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ranyk.activiti.po

#log
logging:
  level:
    com:
      ranyk: debug


